services:
  ads_scan_explorer_ui:
    ports:
      - "3000:3000"
    entrypoint: npm run dev
    environment:
      - METADATA_SERVICE_URL=http://ads_scan_explorer_service:8181/metadata
      - MANIFEST_SERVICE_URL=http://ads_scan_explorer_service:8181/manifest
      - IMAGE_SERVER_URL=http://ads_scan_explorer_cantaloupe:8182/iiif/2