version: '3.1'
networks:
  ads_scan_explorer_network:
      name: ads_scan_explorer_network
      external: true
services:
  ads_scan_explorer_ui:
    container_name: "ads_scan_explorer_ui"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: ads_scan_explorer_ui:latest
    volumes:
    - ./:/app
    networks:
      - ads_scan_explorer_network